---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP présente des limites de configuration du stockage dans Google Cloud pour assurer la fiabilité des opérations. Pour des performances optimales, ne configurez pas votre système aux valeurs maximales. 
---
= Limites de stockage dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP présente des limites de configuration du stockage pour assurer des opérations fiables. Pour des performances optimales, ne configurez pas votre système aux valeurs maximales.



== Capacité système maximale par licence

La capacité système maximale d'un système Cloud Volumes ONTAP est déterminée par sa licence. La capacité système maximale inclut le stockage sur disque et le stockage objet utilisé pour le Tiering des données. NetApp ne prend pas en charge le dépassement de cette limite.

Pour certaines configurations, les limites de disque vous empêchent d'atteindre la limite de capacité en utilisant uniquement des disques. Vous pouvez atteindre la limite de capacité de https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["tiering des données inactives vers le stockage objet"^]. Pour plus de détails, reportez-vous aux limites de disques ci-dessous.

[cols="25,75"]
|===
| Licence | Capacité système maximale (disques + stockage objet) 


| Fréemium | 500 GO 


| PAYGO Explore | 2 To (le Tiering des données n'est pas pris en charge par Explore) 


| PAIEMENT À L'UTILISATION Standard | 10 TO 


| PAIEMENT À L'UTILISATION Premium | 368 TO 


| Licence basée sur les nœuds | 368 To par licence 


| Licence basée sur la capacité | 2 Pio 
|===


== Limites de disque et de hiérarchisation

Le tableau ci-dessous présente la capacité maximale du système avec des disques seuls et des disques avec Tiering des données inactives vers le stockage objet. Les limites de disque sont spécifiques aux disques qui contiennent des données utilisateur. Les limites n'incluent pas le disque d'amorçage et le disque racine.

[cols="60,40"]
|===
| Paramètre | Limite 


| Nombre maximal de disques par système | 124 


| Taille maximale des disques | 16 TO 


| Capacité système maximale avec disques seuls | 256 TO 


| Capacité système maximale avec disques et Tiering des données inactives vers un compartiment Google Cloud Storage | Dépend de la licence. Voir le tableau ci-dessus. 
|===


== Restrictions agrégées

Cloud Volumes ONTAP regroupe les disques Google Cloud Platform dans des _aggrégats_. Les agrégats fournissent du stockage aux volumes.

[cols="2*"]
|===
| Paramètre | Limite 


| Nombre maximal d'agrégats de données | 99 ^1^ 


| Taille maximale des agrégats | 96 To de capacité brute ^2^ 


| Disques par agrégat | 1-6 ^3^ 


| Nombre maximal de groupes RAID par agrégat | 1 
|===
Remarques :

. Le nombre maximal d'agrégats de données n'inclut pas l'agrégat racine.
. La limite de capacité de l'agrégat dépend des disques qui composent l'agrégat. La limite n'inclut pas le stockage objet utilisé pour le Tiering des données.
. Tous les disques qui composent un agrégat doivent être de la même taille.




== Limites de stockage logique

[cols="22,22,56"]
|===
| Stockage logique | Paramètre | Limite 


| *Machines virtuelles de stockage (SVM)* | Nombre maximum pour Cloud Volumes ONTAP | Un SVM de service des données et un SVM de destination utilisés pour la reprise après incident. Vous pouvez activer le SVM de destination pour l'accès aux données en cas de panne sur le SVM source. ^1^ le seul SVM qui transmet les données à l'ensemble du système Cloud Volumes ONTAP. 


.2+| *Fichiers* | Taille maximale | 16 TO 


| Maximum par volume | Selon la taille du volume, jusqu'à 2 milliards 


| *Volumes FlexClone* | Profondeur de clone hiérarchique ^2^ | 499 


.3+| *Volumes FlexVol* | Maximale par nœud | 500 


| Taille minimale | 20 MO 


| Taille maximale | 100 TO 


| *Qtrees* | Maximum par volume FlexVol | 4,995 


| *Copies snapshot* | Maximum par volume FlexVol | 1,023 
|===
Remarques :

. Cloud Manager ne prend pas en charge la configuration ou l'orchestration de la reprise après incident SVM. Il ne prend pas non plus en charge les tâches relatives au stockage sur une SVM supplémentaire. Vous devez utiliser System Manager ou l'interface de ligne de commande pour la reprise après incident SVM.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guide de préparation rapide pour la reprise après incident du SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guide de reprise après incident de SVM Express"^]


. La profondeur de clone hiérarchique correspond à la profondeur maximale d'une hiérarchie imbriquée de volumes FlexClone qui peut être créée à partir d'un seul volume FlexVol.




== Limites de stockage iSCSI

[cols="3*"]
|===
| Stockage iSCSI | Paramètre | Limite 


.4+| *LUN* | Maximale par nœud | 1,024 


| Nombre maximal de mappages de LUN | 1,024 


| Taille maximale | 16 TO 


| Maximum par volume | 512 


| *igroups* | Maximale par nœud | 256 


.2+| *Initiateurs* | Maximale par nœud | 512 


| Maximum par groupe initiateur | 128 


| *Sessions iSCSI* | Maximale par nœud | 1,024 


.2+| *Lifs* | Maximum par port | 1 


| Maximum par ensemble de ports | 32 


| *Porsets* | Maximale par nœud | 256 
|===