---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s 
summary: Ces limitations connues sont spécifiques à Cloud Volumes ONTAP dans Amazon Web Services. 
---
= Restrictions connues dans AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes sont spécifiques à Cloud Volumes ONTAP dans Amazon Web Services. N'oubliez pas de consulter également link:reference-limitations.html["Restrictions applicables dans tous les fournisseurs de cloud"].



== Paires HAUTE DISPONIBILITÉ non prises en charge avec les montants AWS

Les systèmes à un seul nœud sont pris en charge avec des systèmes d'externalisation AWS, mais les paires haute disponibilité ne sont pas prises en charge pour l'instant.



== Limites de Flash cache

Les types d'instances C5D et R5D incluent le stockage NVMe local, que Cloud Volumes ONTAP utilise comme _Flash cache_. Notez les limites suivantes :

* La compression doit être désactivée sur tous les volumes pour tirer parti des améliorations des performances de Flash cache.
+
Vous pouvez choisir aucune efficacité du stockage lors de la création d'un volume depuis Cloud Manager, ou encore créer un volume, puis http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Désactiver la compression des données à l'aide de l'interface de ligne de commande"^].

* La réactivation du cache après un redémarrage n'est pas prise en charge avec Cloud Volumes ONTAP.




== Fausses alarmes signalées par Amazon CloudWatch

Cloud Volumes ONTAP ne libère pas les processeurs lorsqu'ils sont inactifs https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] Peut signaler un avertissement CPU élevé pour l'instance EC2 car celui-ci détecte une utilisation à 100 %. Vous pouvez ignorer cette alarme. La commande ONTAP statistics affiche la véritable utilisation des CPU.



== Les paires haute disponibilité Cloud Volumes ONTAP ne prennent pas en charge le rétablissement immédiat du stockage

Après le redémarrage d'un nœud, le partenaire doit synchroniser les données pour qu'il puisse renvoyer le système de stockage. Le temps nécessaire pour resynchroniser les données dépend de la quantité de données écrites par les clients alors que le nœud était en panne et de la vitesse d'écriture des données pendant le rétablissement.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha.html["Découvrez le fonctionnement du stockage dans une paire haute disponibilité Cloud Volumes ONTAP s'exécutant dans AWS"^].



== Limitations de l'environnement AWS C2S

Consultez les limites de la documentation Cloud Manager : https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html["Lancez-vous dans l'environnement AWS C2S"^]
